# Generated by Django 5.2.17 on 2026-08-16 20:27

import django.db.models.deletion
from django.db import migrations, models


# The partitioned decisions table, written out because Django cannot express it.
#
# Postgres requires the partition key in every unique constraint, which is why
# the primary key is (id, decided_at) rather than id alone — and why the
# idempotency guarantee lives in its own unpartitioned table instead of a
# constraint here. See the docstring on complylayer.models.Decision.
CREATE_DECISION = """
CREATE TABLE complylayer_decision (
    id                 varchar(32)  NOT NULL,
    decided_at         timestamptz  NOT NULL,
    tenant_id          varchar(32)  NOT NULL REFERENCES complylayer_tenant(id) DEFERRABLE INITIALLY DEFERRED,
    idempotency_key    varchar(128) NOT NULL,
    ruleset_version    integer      NOT NULL CHECK (ruleset_version >= 0),
    transaction_ref    varchar(128) NOT NULL,
    customer_ref_hash  varchar(64)  NOT NULL,
    amount_minor       bigint       NOT NULL,
    currency           varchar(3)   NOT NULL,
    context            jsonb        NOT NULL,
    resolved_facts     jsonb        NOT NULL DEFAULT '{}'::jsonb,
    outcome            varchar(16)  NOT NULL,
    matched_rules      jsonb        NOT NULL DEFAULT '[]'::jsonb,
    shadow_matches     jsonb        NOT NULL DEFAULT '[]'::jsonb,
    reason             text         NOT NULL DEFAULT '',
    degraded           boolean      NOT NULL DEFAULT false,
    errored_rules      jsonb        NOT NULL DEFAULT '[]'::jsonb,
    latency_ms         integer      NOT NULL CHECK (latency_ms >= 0),
    review_status      varchar(16)  NOT NULL DEFAULT '',
    reviewed_by        varchar(64)  NOT NULL DEFAULT '',
    review_notes       text         NOT NULL DEFAULT '',
    PRIMARY KEY (id, decided_at)
) PARTITION BY RANGE (decided_at);

CREATE INDEX complylayer_decision_decided_at ON complylayer_decision (decided_at);
CREATE INDEX complylayer_decision_txn_ref    ON complylayer_decision (transaction_ref);
CREATE INDEX complylayer_decision_customer   ON complylayer_decision (customer_ref_hash);
CREATE INDEX complylayer_decision_review     ON complylayer_decision (tenant_id, review_status, decided_at);
CREATE INDEX complylayer_decision_outcome    ON complylayer_decision (tenant_id, outcome, decided_at);

-- A catch-all so a decision can never fail to land because nobody remembered to
-- create next month's partition. Rows here are a signal that the partition
-- maintenance job has stopped, not a normal condition.
CREATE TABLE complylayer_decision_default PARTITION OF complylayer_decision DEFAULT;
"""

DROP_DECISION = "DROP TABLE IF EXISTS complylayer_decision CASCADE;"


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("fallback_policy", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "complylayer_tenant",
            },
        ),
        migrations.CreateModel(
            name="RuleSetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("rules_snapshot", models.JSONField()),
                ("lists_snapshot", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("published_by", models.CharField(max_length=64)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rulesets",
                        to="complylayer.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "complylayer_rulesetversion",
                "unique_together": {("tenant", "version")},
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("id", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(max_length=64)),
                ("regulatory_reference", models.CharField(blank=True, max_length=255)),
                ("expression", models.TextField()),
                ("severity", models.CharField(max_length=16)),
                ("priority", models.IntegerField(default=0)),
                ("applies_to", models.JSONField(blank=True, default=dict)),
                ("customer_message", models.TextField(blank=True)),
                ("state", models.CharField(default="draft", max_length=16)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_by", models.CharField(max_length=64)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="complylayer.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "complylayer_rule",
                "indexes": [
                    models.Index(fields=["tenant", "state"], name="complylayer_tenant__55f88b_idx")
                ],
                "unique_together": {("tenant", "name", "version")},
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("decision_id", models.CharField(max_length=32)),
                ("decision_decided_at", models.DateTimeField()),
                ("response_body", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency",
                        to="complylayer.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "complylayer_idempotency",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "key"), name="idempotency_key_per_tenant"
                    )
                ],
            },
        ),
        # Decision is the one table that has to be partitioned from the very
        # first migration (D10). Django has no declarative support for it, so
        # the table is created by hand and the model is registered in Django's
        # state separately. Retrofitting partitioning onto a table holding
        # years of decisions is a project; doing it now costs this block.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Decision",
                    fields=[
                        ("id", models.CharField(max_length=32)),
                        ("decided_at", models.DateTimeField(db_index=True)),
                        (
                            "pk",
                            models.CompositePrimaryKey(
                                "id",
                                "decided_at",
                                blank=True,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("idempotency_key", models.CharField(max_length=128)),
                        ("ruleset_version", models.PositiveIntegerField()),
                        ("transaction_ref", models.CharField(db_index=True, max_length=128)),
                        ("customer_ref_hash", models.CharField(db_index=True, max_length=64)),
                        ("amount_minor", models.BigIntegerField()),
                        ("currency", models.CharField(max_length=3)),
                        ("context", models.JSONField()),
                        ("resolved_facts", models.JSONField(blank=True, default=dict)),
                        ("outcome", models.CharField(max_length=16)),
                        ("matched_rules", models.JSONField(default=list)),
                        ("shadow_matches", models.JSONField(default=list)),
                        ("reason", models.TextField(blank=True)),
                        ("degraded", models.BooleanField(default=False)),
                        ("errored_rules", models.JSONField(blank=True, default=list)),
                        ("latency_ms", models.PositiveIntegerField()),
                        ("review_status", models.CharField(blank=True, max_length=16)),
                        ("reviewed_by", models.CharField(blank=True, max_length=64)),
                        ("review_notes", models.TextField(blank=True)),
                        (
                            "tenant",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="decisions",
                                to="complylayer.tenant",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "complylayer_decision",
                        "indexes": [
                            models.Index(
                                fields=["tenant", "outcome", "decided_at"],
                                name="complylayer_tenant__4baeda_idx",
                            ),
                            models.Index(
                                fields=["tenant", "review_status", "decided_at"],
                                name="complylayer_tenant__d9cefa_idx",
                            ),
                        ],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(sql=CREATE_DECISION, reverse_sql=DROP_DECISION),
            ],
        ),
        migrations.CreateModel(
            name="AuditRecord",
            fields=[
                ("id", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.JSONField(default=dict)),
                ("subject", models.JSONField(default=dict)),
                ("payload", models.JSONField(default=dict)),
                ("prev_hash", models.CharField(blank=True, max_length=71)),
                ("hash", models.CharField(max_length=71)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit",
                        to="complylayer.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "complylayer_auditrecord",
                "indexes": [
                    models.Index(
                        fields=["tenant", "recorded_at"], name="complylayer_tenant__bb7d5c_idx"
                    )
                ],
            },
        ),
    ]
