# Generated by Django 5.2.17 on 2026-08-16 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complylayer', '0002_audit_immutability'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('values', models.JSONField(default=list)),
                ('updated_by', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lists', to='complylayer.tenant')),
            ],
            options={
                'db_table': 'complylayer_namedlist',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='named_list_per_tenant')],
            },
        ),
    ]
