# Generated by Django 5.2.17 on 2026-08-16 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complylayer', '0003_namedlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('prefix', models.CharField(db_index=True, max_length=24, unique=True)),
                ('hashed_secret', models.CharField(max_length=255)),
                ('environment', models.CharField(default='live', max_length=8)),
                ('role', models.CharField(max_length=32)),
                ('created_by', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='complylayer.tenant')),
            ],
            options={
                'db_table': 'complylayer_apikey',
                'indexes': [models.Index(fields=['tenant', 'environment'], name='complylayer_tenant__8ab81a_idx')],
            },
        ),
    ]
