# Generated by Django 5.2.17 on 2026-08-19 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complylayer', '0009_dashboard_user_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCheckpoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chain_length', models.IntegerField()),
                ('head_hash', models.CharField(max_length=80)),
                ('signed_at', models.DateTimeField()),
                ('signature', models.CharField(max_length=256)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_checkpoints', to='complylayer.tenant')),
            ],
            options={
                'db_table': 'complylayer_auditcheckpoint',
                'indexes': [models.Index(fields=['tenant', '-chain_length'], name='complylayer_tenant__b5c83c_idx')],
            },
        ),
    ]
